### ISSUE TITLE
documentation: Update component design guidelines event examples

### ISSUE THREAD

**Issue by vances** [tmforum-oda/oda-ca-docs#20]
## Description

Update the example for events in Component Design Guidelines to reflect the ODA-RI requirements and API team's event schema refactoring.

The syntax should be:
```
  eventNotification:
    publishedEvents:
    - name: <<resource>><<verb>>Event
       href: <<event schema URI>>
```
However we do not yet have URIs for event schemas so completion is blocked until available.
