### ISSUE TITLE
Documentation: Bullet-points are not showing from markdown files

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-ca-docs#91]
## Description

In the generated documentation, Bullet-points (HTML `<UL>` elements) are not showing.

This is probably a styling issue as the HTML content does include the UL elements. I believe the theme.css file is applying a style with `list-style-type` and `list-style` of `none`.

I propose we try to over-ride with:

```css
<style>
ul {
  list-style-type: disc !important;
}
li {
  display: list-item !important;
  list-style: disc !important;
}
</style>
```

**Comment by LesterThomas** [comment]
Issue is still there.

**Comment by LesterThomas** [comment]
The issue is still there. You can manually work-around by editing the theme.css file in gh-pages to add the `div.wy-menu` to the ul style (to make it specific to just the navigation).

```css
dl,
ol,
div.wy-menu ul {
    margin: 0;
    padding: 0;
    list-style: none;
    list-style-image: none
}

div.wy-menu ul li {
    list-style: none
}
```

I need to somehow add this to the automation.
